CREATE TABLE IF NOT EXISTS `VEHICLE_TYPE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `FRAME` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `MATERIAL` VARCHAR(32) NOT NULL,
  `VEHICLE_TYPE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_FRAME_VEHICLE_TYPE_ID` FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `VEHICLE_TYPE` (`ID`)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `POWERTRAIN` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(32) NOT NULL,
  `VEHICLE_TYPE_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_POWERTRAIN_VEHICLE_TYPE_ID` FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `VEHICLE_TYPE` (`ID`)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `WHEEL` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `VEHICLE_TYPE_ID` BIGINT NOT NULL,
  `POSITION` VARCHAR(32) NOT NULL DEFAULT 'NONE',
  `MATERIAL` VARCHAR(32),
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_WHEEL_VEHICLE_TYPE_ID` FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `VEHICLE_TYPE` (`ID`)
  ON DELETE CASCADE ON UPDATE CASCADE
);